version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: docker-postgresql
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=cliente_db
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  postgres_data:
    driver: local
